### ISSUE TITLE
Provide Tagged Releases (for melpa-stable)

### ISSUE THREAD

**Issue by the-kenny** [rust-lang/rust-mode#179] opened 2016-10-31 10:18 UTC
It would be very useful to have tagged releases of `rust-mode`. Main benefits are:

a) Known working versions - not every user wants to run a random git revision
b) Visibility in `melpa-stable`: Instead of using nightly snapshots `melpa-stable` uses the latest tagged release of a package
c) If tracking rustc-releases, one could always use the version of `rust-mode` that works for the current compiler

A simple `git tag v1.12.0` on a known-good revision is enough and would provide much value.

**Comment by MicahChalmer** [comment] 2016-11-01 04:11
Closing as a dupe of #87.  Also see #178 - there's a tag for 0.3.0 now.

**Closed by MicahChalmer** 2016-11-01 04:11 UTC
