### ISSUE TITLE
Disabling automatic brace insertion

### ISSUE THREAD

**Issue by 949f45ac** [rust-lang/rust-mode#512] opened 2024-02-16 06:08 UTC
Hey there, landed here from https://github.com/brotzeit/rustic/issues/541

To recap, I am looking for a way to disable the emacs behavior where it inserts closing braces automatically in my Rust code, when I try to add braces to an existing piece of code somewhere.

The added braces (both normal and curly) are reliably in the wrong spot, and I cannot even outsmart the feature by inserting the non-matched closing brace first – it will still insist on adding another closing brace, reliably in a stupid spot.

I get generally unnerved when my editor inserts characters without me typing them. In this case the auto-edit’s quality is especially horrendous.

I am not sure rust-mode is to blame, I searched through the code briefly and did not find a lead. Please point me to the culprit. I have made sure that electric-pair-mode is not to blame, by explicitly toggling it off (it was already off).

**Comment by psibi** [comment] 2024-02-17 05:56
I'm not able to reproduce the behavior, but I'm using the treesitter based mode implemented in this PR: https://github.com/rust-lang/rust-mode/pull/482

**Comment by benjamin-sieffert** [comment] 2024-02-28 10:27
Great, the problem does indeed go away when using the treesitter-based mode.
Please keep it this way, and never add any automatic characters to that mode.

By the way, it was a bit hard for me to get to work, emacs kept looking for `libtree-sitter-rust.so` and not finding it. I tried installing the `tree-sitter-langs` package, which indeed comes with rust, but the library is called only `rust.so` so that also did not work.
I had to install this package from AUR: https://aur.archlinux.org/packages/tree-sitter-rust
Don’t know if this is the intended experience, reading just through this repo’s README it didn’t seem like any special installation steps would be required.

**Comment by psibi** [comment] 2024-02-28 10:34
> Please keep it this way, and never add any automatic characters to that mode.

Yeah, that's the plan. Maybe some helper functions to navigate, but I want to leave most of the things to tree sitter.

> Don’t know if this is the intended experience, reading just through this repo’s README it didn’t seem like any special installation steps would be required.

I have heard from others that the installation experience is not that good yet. Feel free to send a documentation patch to update the README with instructions for your OS.

Thanks for the confirmation, I'm closing the issue since it's fixed.

**Closed by psibi** 2024-02-28 10:34 UTC

**Comment by vaab** [comment] 2024-07-25 15:14
Let me repost here also my answer for other people looking for pointers (as I did): you should try setting `lsp-enable-on-type-formatting` to `nil`. This is a rust-analyzer bug (cf: https://github.com/rust-lang/rust-analyzer/issues/16084 for more info). The latter post is suggesting to run the function (`lsp-toggle-on-type-formatting`), which drives the former variable and do some upkeeping of hooks after toggling the variable's value. I had more success with `nil` in the variable at rustic setup time so I guess it would be the same for `rust-mode`.
