### ISSUE TITLE
Adding a line break after a Trait in a template argument list breaks emacs-mode indentation

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust-mode#10] opened 2015-02-02 10:16 UTC
<a href="https://github.com/gsingh93"><img src="https://avatars.githubusercontent.com/u/1012677?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gsingh93](https://github.com/gsingh93)**
_Friday Aug 22, 2014 at 01:25 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/16665_

_This issue was labelled with: A-infrastructure in the Rust repository_

----

I think this is a somewhat serious bug with emacs-mode, since I can't use the tab key for indentation inside a function block in many cases.

My code ends up with a long list of traits with bounds in the template argument list, and according to the [style guide](https://aturon.github.io/style/whitespace.html#line-wrapping), I can wrap between traits. However, if I wrap between traits, identation is broken for the function. Consider the following example,
```
pub fn foo<T,
           V>() {
              // Indentation puts me here
}
```
As you can see, hitting tab inside the function idents too much. I should mention that I aligned the second template argument to match up with the first, as hitting tab there doesn't work either.

**Comment by GBGamer** [comment] 2015-04-14 02:24
Okay, the problem is with `(backward-up-list)`. When run in the first case:

```rust
pub fn test(...
	   |...) -> Test {
           ^ Point is here
}
```

it moves to

```rust
pub fn test|(...
	   ^ Point is here now
	     ...) -> Test {
}
```

However, when run with the ->, goes from

```rust
pub fn test(...)
	   |-> Test {
           ^ Point is here
}
```

to

```rust
pub fn test(...)
           |-> Test {
           ^ Point is here
}

As you can see, the point doesn't actually move at all. I'm working on some fixes.

**Comment by GBGamer** [comment] 2015-04-14 03:11
This is now fixed? Another bug shows up:

```rust
fn test<A,
V>(_a: A, _v: V) {
^ The indentation starts here...
}
```

**Comment by GBGamer** [comment] 2015-04-14 03:17
The second issue is one with `(backward-up-list)`:

```rust
mod test |2| {
    fn test|3|<A,|1|
                V>() {
```

The cursor goes from `|1|` to `|2|`, when it should go from `|1|` to `|3|`.

**Comment by MicahChalmer** [comment] 2015-04-14 03:32
To make `backward-up-list` go where it should, emacs would have to recognize the `<` and `>` angle brackets as parentheses in its syntax table.  In theory it's possible to do it perfectly, since rust's grammar does not require you to know the symbol table to make this distinction (unlike C++.)

I've been trying to get it to do just that recognizing angle brackets but not mistaking other `<` and `>` characters (return type arrows, match arrows, less than and greater than operators, etc).  At this point I have something that _almost_ works.  Under normal circumstances it fixes this issue.  It also makes the normal paren matching modes work on them without the code to simulate it that's there now (taking care of #50 in the process.)

Unfortunately at this point there are still a few cases where it gets the angle bracket identification wrong.  The other problem with the patch as I currently have it is performance--on my machine, it makes emacs grind to a halt on even moderately large source files (at 7637 lines, `src/librustc/middle/ty.rs` from the rust tree is enough to make it freeze for minutes.)  If anyone is curious I can put it up as an incomplete work-in-progress PR, but it's not ready for merging yet.

**Comment by gsingh93** [comment] 2015-05-23 16:12
Is this related to the following indentation problem, or should I make a new issue:

```
if true
        || false {
            // Wrong indentation
    }
```

**Closed** 2015-07-06 19:46 UTC
