### ISSUE TITLE
Provide releases for melpa-stable

### ISSUE THREAD

**Issue by the-kenny** [rust-lang/rust-mode#101] opened 2015-09-21 11:21 UTC
Some people don't want to install bleeding-edge (daily snapshot) emacs lisp packages from Melpa. For those, melpa-stable automatically collects *tagged* releases from Github and publishes those.

It would be very nice if rust-mode could start adding git-tags for releases for it to appear in melpa-stable.

**Comment by Wilfred** [comment] 2015-10-13 22:27
Duplicate of #87.

**Comment by steveklabnik** [comment] 2015-10-13 23:09
Yup, closing as a dup

**Closed by steveklabnik** 2015-10-13 23:09 UTC
