### ISSUE TITLE
RFE: cargo compilation integration

### ISSUE THREAD

**Issue by frozencemetery** [rust-lang/rust-mode#98] opened 2015-09-20 04:46 UTC
It would be great to integrate with cargo in a manner similar to how compilation works in other modes (run a command to compile; "C-c C-c" or "M-x compile" or such, and then "C-x `" ("M-x next-error") to jump to the next error in the source file).

Although "M-x compile" can be set to invoke `cargo build`, this integrates poorly with next-error since the output is not really formatted for use with that, and a lot of things are selected as errors in the compile output that really aren't.

**Comment by blaenk** [comment] 2015-09-20 04:50
Yeah this would be great. The output could really benefit from some nicer formatting, see #92. And yeah, a lot of times the first error (?) is properly highlighted but if I go past it then want to go back, it won't select it (with M-n and M-p).

**Comment by the-kenny** [comment] 2015-09-22 09:19
Integrating ```next-error``` etc. shouldn't be too hard as it's designed so developers can adapt the regular expressions catching errors. A big benefit of Rust is that the tooling is very "standard", so I think rust-mode should strife for a *simple* solution first (by integrating into existing tooling like ```M-x compile```)

**Comment by AtticHacker** [comment] 2015-10-13 08:52
For what it's worth, I created a package for Cargo integration a few days ago. 
https://github.com/attichacker/cargo.el

Currently doesn't have ````next-error```` support, but that's something I could work on.

**Comment by the-kenny** [comment] 2015-10-17 17:12
@AtticHacker Any reason why you didn't use ```compile``` as a base? I think it's generally nicer to use existing well-known infrastructure instead of inventing your own. 

Rolling your own stuff always means more trouble for the user: New unknown keybindings, incompatibility with existing tools and customizations, etc. etc.

**Comment by AtticHacker** [comment] 2015-10-17 21:24
@the-kenny Good question, the answer is simply that I wasn't aware of compilation-mode! I've changed my package so that it uses it now. I have to say I'm quite surprised how well it works out of the box.

**Comment by the-kenny** [comment] 2015-10-17 21:49
@AtticHacker Awesome :) I'll give it a shot this weekend.

**Comment by MicahChalmer** [comment] 2015-10-18 00:46
`rust-mode` has code in it that is intended to make `next-error` find errors correctly when cargo and/or rustc are run through `compile`.  It looks like as of now it behaves correctly for actual errors, but misbehaves on the notes. That's a bug that should be fixed.

Besides not handling notes correctly, are there other issues anyone is seeing when running cargo through `compile`?

**Comment by blaenk** [comment] 2015-10-18 19:41
Yeah, the one I mentioned [here](https://github.com/rust-lang/rust-mode/issues/98#issuecomment-141748417), although I don't know if it's caused by notes, in which case it's covered by what you said.

Aside from that, there's #92 although those aren't really issues, more like annoyances. One is that the path shown for each error/note/warning is the absolute path of the file, which can be very long and cause annoying wrapping on the error/note/warning messages. If it's not possible to show a relative path (preferably relative to the cargo root, which I think is how cargo shows it by default though I don't remember exactly), it would be nice if it were possible to start the error message on its own line, after the file line:column information.

**Comment by brotzeit** [comment] 2019-09-23 07:42
I think this should be fine now. If not, feel free to open another issue.

**Closed by brotzeit** 2019-09-23 07:42 UTC
