### ISSUE TITLE
Make rust-mode available on melpa stable repository

### ISSUE THREAD

**Issue by markokocic** [rust-lang/rust-mode#125] opened 2016-02-29 09:44 UTC
To make it available at melpa stable, it should be enough just to provide a git tag of the release.

**Comment by vyp** [comment] 2016-02-29 10:14
That is correct.

**Comment by tomjakubowski** [comment] 2016-02-29 20:00
I think this is a dupe of #87.

**Comment by MicahChalmer** [comment] 2016-03-10 01:22
Closing as a dupe of #87.

**Closed by MicahChalmer** 2016-03-10 01:22 UTC
