### ISSUE TITLE
Significant slowdown with rust-match-angle-brackets non nil

### ISSUE THREAD

**Issue by stianeklund** [rust-lang/rust-mode#208] opened 2017-04-28 08:30 UTC
I'm experiencing serious slowdowns when entering insert mode & navigating in general all of a sudden.
Not sure what the cause is but figured I'd create an issue as it doesn't happen with `rust-mode` turned off.

Here's the output from the profiler-report:

```

Function                            Cpu samples   %

timer-event-handler                       13844  92%
command-execute                             782   5%
 ...                                        187   1%
redisplay_internal (C function)             169   1%
eldoc-pre-command-refresh-echo-area           5   0%
sp--save-pre-command-state                    3   0%

```

If I expand `timer-event-handler`, most of the CPU is being hogged on `rust-in-macro` within the `up-list` function. Also `backward-up-list` hogs a good chunk of CPU.
```
 - apply                                                         2171  77%
  - hl-paren-highlight                                           2090  74%
   - scan-sexps                                                  2077  74%
    - internal--syntax-propertize                                2077  74%
     - syntax-propertize                                         2077  74%
      - rust-syntax-propertize                                   2073  74%
       - rust-ordinary-lt-gt-p                                   2073  74%
        - rust-in-macro                                          1955  69%
         + rust-in-macro                                         1615  57%
         + backward-up-list                                       241   8%
         + rust-rewind-irrelevant                                  95   3%
         + rust-looking-back-ident                                  4   0%
        + rust-in-str-or-cmnt                                     118   4%
```
Anyone experienced anything similar?

Same issue on current nightly & stable (1.17) I've tried with a clean .spacemacs file and without any additional packages. It's only when `rust-mode` is enabled I run into this slowdown.

The file I'm working on is less than 1k lines.

Also as an aside, I've tried Emacs24, Ubuntu 15.04, 16.04 and now upgraded to 16.10.
This is on a Virtual machine.

```
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
```

**Comment by tromey** [comment] 2017-04-28 13:41
Sounds like a regression due to the syntax propertization patch; but the spacemacs part makes me wary, I don't really know spacemacs and in many ways it is its own thing.  I wonder if there's a way to reproduce without it.

**Comment by stianeklund** [comment] 2017-04-28 14:49
@tromey Now for some reason it works great without any slowdowns. I can't reproduce this issue now anymore for some weird reason. I wish I had something to bring to the table here but I do not.

I'll try upgrading my computer at home and see if I run into the same issues.

**Comment by fafhrd91** [comment] 2017-05-04 18:47
same for me. emacs is unusable with rust-mode enabled

**Comment by fafhrd91** [comment] 2017-05-04 19:18
I can confirm, downgraded to 35298ed93dd6a71fa09d9e1cb6dbd610871f4e2b and it works good again

**Comment by stianeklund** [comment] 2017-05-05 07:23
@fafhrd91 Thanks, at least there is a workaround for now.

**Comment by tromey** [comment] 2017-05-06 04:34
I think the best thing to do would be to file a bug against Spacemacs, because it seems to me that the underlying problem must lie there.

**Comment by fafhrd91** [comment] 2017-05-06 05:25
I have this problem with emacs 25.2

**Comment by tromey** [comment] 2017-05-06 14:56
> I have this problem with emacs 25.2

Aha, I didn't realize, thanks.  Can you reproduce it with `emacs -Q`?  If not then I may need to see what packages you have installed.

**Comment by fafhrd91** [comment] 2017-05-06 15:27
I also noticed, sometime emacs locks if I start edit comment. for example, open new rust file and start typing "//" in first line, after this "//" emacs is dead and I have to kill with kill -9

**Comment by mfeckie** [comment] 2017-05-20 14:31
I have the same issue as stianeklund,  running profiler gives almost exactly the same trace with the majority of time being spent in `rust-in-macro`

**Comment by stianeklund** [comment] 2017-06-12 08:59
Just wanted to chime in on this, I'm still having this problem a lot. I've tested a myriad versions, and have concluded it's not related to the version of Emacs, just tested version 24.5.1. It's definitely a regression in rust-mode. Please let me know if you need any help in narrowing down the issue. I believe @mfeckie & me have the same problem.

**Comment by cvb** [comment] 2017-06-26 05:46
Having same issue, sometimes actions with rust code end in ~3 second freeze. The good news, I don't have this issue if I start `emacs -Q` with only `rust-mode` package. Bad  news, now I have absolutely no Idea what to do next, profiler clearly shows that the problem is inside this mode.

**Comment by fmdkdd** [comment] 2017-08-20 20:07
I can confirm a reproducible ~3 second freeze as well in `emacs -Q`:

1. Open `emacs -Q`
2. Eval `(package-initialize)`
3. Copy the content of [this Rust file](https://raw.githubusercontent.com/rust-lang/cargo/master/src/cargo/ops/cargo_rustc/mod.rs) in the buffer
4. `M-x rust-mode`
5. `M-x auto-fill-mode`
6. Go to the end of a line 909: `M-x goto-line 909 RET C-e`
7. Insert spaces at the end of line (leave the spacebar pressed)
8. The cursor stutters, then freezes for a few seconds

```
Emacs version: GNU Emacs 25.2.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.16) of 2017-07-16
rust-mode.el version: 20170805.952
```

`profiler-report` indicates that `rust-syntax-propertize` is the likely culprit, with more than half the time spent in `rust-in-macro`:
```
- command-execute                                                5696  96%
 - call-interactively                                            5695  96%
  - funcall-interactively                                        5671  95%
   - self-insert-command                                         5652  95%
    - rust-do-auto-fill                                          5652  95%
     - rust-with-comment-fill-prefix                             5652  95%
      - #<compiled 0x8913db>                                     5628  94%
       - apply                                                   5628  94%
        - do-auto-fill                                           5628  94%
         - fill-context-prefix                                   5618  94%
          - fill-match-adaptive-prefix                           5618  94%
           - rust-find-fill-prefix                               5566  93%
            - rust-in-comment-paragraph                          5563  93%
             - syntax-ppss                                       5560  93%
              - syntax-propertize                                5560  93%
               - rust-syntax-propertize                          5524  93%
                - rust-ordinary-lt-gt-p                          5391  90%
                 - rust-in-macro                                 3258  54%
                  - rust-in-macro                                1431  24%
                   + rust-in-macro                                486   8%
                   + rust-rewind-irrelevant                       371   6%
                   + backward-up-list                             268   4%
                   + rust-paren-level                             240   4%
                   + rust-looking-back-ident                       36   0%
                   + backward-sexp                                  3   0%
                  + rust-rewind-irrelevant                        968  16%
                  + rust-paren-level                              388   6%
                  + backward-up-list                              345   5%
                  + rust-looking-back-ident                        79   1%
                  + backward-sexp                                   9   0%
                    rust-looking-back-str                           6   0%
                 + rust-is-lt-char-operator                      1465  24%
                 + rust-in-str-or-cmnt                            476   8%
                 + rust-paren-level                               150   2%
                 + backward-up-list                                 7   0%
                + rust--syntax-propertize-raw-string                 37   0%
                  #<compiled 0x3787db>                              3   0%
             + #<compiled 0x71cb7f>                                 3   0%
           + current-left-margin                                   52   0%
         + fill-forward-paragraph                                  10   0%
      + syntax-ppss                                                24   0%
   + execute-extended-command                                      15   0%
  + byte-code                                                      24   0%
+ ...                                                             197   3%
+ redisplay_internal (C function)                                  34   0%
```

**Comment by tromey** [comment] 2017-08-28 03:26
I've been looking into this a bit.

One oddity here is that it seems to me that `rust-do-auto-fill` shouldn't even be called in this situation.  My view is that `comment-auto-fill-only-comments` should be `t` in all programming modes (though just setting this isn't enough, a bug I recently fixed for Emacs 26).

If I wrap `rust-do-auto-fill` in a check for `(nth 4 (syntax-ppss))`, the performance here is fine.  Perhaps I should push this...

`rust-in-macro` has some maybe mildly questionable bits as well, though.  So perhaps it could be improved; though I'm not certain whether that would be enough.

Earlier reports here didn't seem to rely on auto filling.  I'll investigate those as well.

**Comment by topecongiro** [comment] 2017-10-06 06:57
FWIW, to workaround this `(setq rust-match-angle-brackets nil)` works for me. It basically prevents `rust-in-macro` from being called. We lose syntax highlighting on angle brackets in exchange, though.

**Comment by theindigamer** [comment] 2017-12-13 01:54
Related: https://github.com/raxod502/radian/issues/392 . FWIW, I used a similar solution as suggested there; I added `adaptive-wrap` to `dotspacemacs-excluded-packages`.
I tried using `(remove-hook 'rust-mode-hook 'adaptive-wrap-prefix-mode)` in `dotspacemacs/user-config` but that didn't work.

**Comment by pcx** [comment] 2018-04-01 15:19
I too am having this problem with Emacs 25.3.1 and rust-mode 20180322.127. Emacs freezes in some cases, and I am able to reproduce it for certain operations. Would love to have a fix for this. Please let me know if you need anything from me. Thanks.

cc: @tromey

**Comment by fafhrd91** [comment] 2018-04-01 15:26
I can reproduce it pretty easily. create new file.rs file and enter `//!` at this point emacs is dead

**Comment by schell** [comment] 2019-06-07 20:49
Still running into this here on spacemacs :(

**Comment by stianeklund** [comment] 2019-06-19 10:23
@schell Yes same here, I've moved on from Spacemacs at the moment and use IDEA until this is (hopefully) fixed. This isn't just a Spacemacs issue unfortunately.

**Comment by kccqzy** [comment] 2020-01-20 06:42
I can confirm this is still an issue. Fortunately, the workaround in https://github.com/rust-lang/rust-mode/issues/208#issuecomment-334674510 works.

**Comment by mookid** [comment] 2020-01-29 00:48
Hi @kccqzy,

do you have a reproduction case? I did not encounter this myself (and references made earlier are dead links).

**Comment by phillord** [comment] 2020-04-17 11:44
I am getting this on Emacs-27, using a clean emacs. It happens on many rust files. Likewise, the `rust-match-angle-brackets` fix seems to work and rust-in-macro seems to be the main cause of the problem.

Not sure what the problem is the with the implementation of rust-in-macro. I will investigate.

**Comment by phillord** [comment] 2020-04-17 11:45
Can we update the bug heading? It's not Spacemacs, nor Emacs 25 after all!

**Comment by mookid** [comment] 2020-04-17 17:12
Changed the title. Still, any reproduction step would be welcome.

**Comment by schell** [comment] 2020-04-18 19:10
@mookid there's a number of different reproduction scenarios in the posts above :)

**Comment by phillord** [comment] 2020-04-22 22:07
The fundamental problem here is that `rust-ordinary-lt-gt-p` is called from `rust-syntax-propertize` which in turns calls `rust-in-macro`.  In my current buffer, it is getting called repeated (like 60 or 70 times) under almost any circumstances. So, either something badly is going wrong  that is causing this to happen when it shouldn't, or its the normal function of `syntax-propertize-function` and this just has to made to work faster.

Will pick further.

**Comment by phillord** [comment] 2020-04-23 09:24
I've sent in a PR which I think improves things. As "goes faster" is very hard to judge, I'd appreciate others giving this a go.

**Closed** 2020-05-13 08:12 UTC
Labels: bug
