### ISSUE TITLE
*rustfmt* buffer remains empty after rustfmt failure

### ISSUE THREAD

**Issue by spacerainbow000** [rust-lang/rust-mode#248] opened 2017-11-16 18:09 UTC
I'm unable to get anything to show in the rustfmt buffer when I run rustmft against a file that makes rustfmt fail; it's the same whether I do it manually or trigger with a save. I made a breaking edit to an example program:
![image](https://user-images.githubusercontent.com/21026840/32907673-b6270fae-cab5-11e7-8ecf-74fb34e518b5.png)
when I save, I get a message that rustfmt failed, as expected:
![image](https://user-images.githubusercontent.com/21026840/32907698-cb52a3de-cab5-11e7-8890-41cd8bff5e30.png)
then when I open the buffer-menu to go see what the formatting problem is, \*rustfmt\* is only ever empty:
![image](https://user-images.githubusercontent.com/21026840/32907720-e2e17caa-cab5-11e7-987b-f2d36432a36d.png)
when really I'm expecting it to have this info:
![image](https://user-images.githubusercontent.com/21026840/32907731-efeeb1e2-cab5-11e7-9302-afc1aae53667.png)
are my expectations of what should be in the rustfmt buffer after a formatting failure incorrect? Right now I am disabling rustfmt-on-save, saving the file, opening a shell, then running rustfmt against the file from the shell to get info on where my formatting is messed up. This works but is quite tedious.

**Comment by brotzeit** [comment] 2017-11-17 15:00
The problem is that we only insert the contents of the temp file into the rustfmt buffer if the error code is 3. Different exit codes just raise the error you posted and do nothing else.

**Comment by spacerainbow000** [comment] 2017-11-17 20:24
I'm pretty new to emacs, how would I go about changing that behavior?

**Comment by brotzeit** [comment] 2017-11-18 00:18
You can put this in your config



```
;; Formatting using rustfmt
(defun rust--format-call (buf)
  "Format BUF using rustfmt."
  (with-current-buffer (get-buffer-create "*rustfmt*")
    (erase-buffer)
    (insert-buffer-substring buf)
    (let* ((tmpf (make-temp-file "rustfmt"))
           (ret (call-process-region (point-min) (point-max) rust-rustfmt-bin
                                     t `(t ,tmpf) nil)))
      (unwind-protect
          (cond
           ((zerop ret)
            (if (not (string= (buffer-string)
                              (with-current-buffer buf (buffer-string))))
                (copy-to-buffer buf (point-min) (point-max)))
            (kill-buffer))
           ((= ret 3)
            (let ((buffer-read-only nil))
              (if (not (string= (buffer-string)
                                (with-current-buffer buf (buffer-string))))
                  (copy-to-buffer buf (point-min) (point-max)))
              (erase-buffer)
              (insert-file-contents tmpf)
              (error "Rustfmt could not format some lines, see *rustfmt* buffer for details")))
           (t
            (erase-buffer)
            (insert-file-contents tmpf)
            (error "Rustfmt failed, see *rustfmt* buffer for details"))))
      (delete-file tmpf))))
```

**Comment by spacerainbow000** [comment] 2017-11-22 22:16
no dice unfortunately; I was still not seeing anything in the buffer. I tried changing the text of both errors in the code u posted, and was still seeing the original "Rustfmt failed, see \*rustfmt\* buffer for details" when I saved a file with a formatting error.

**Comment by brotzeit** [comment] 2017-11-22 22:45
Hmmmm, I've tried this several times now. Did you use `(require 'rust-mode)` before the snippet ? You can alternatively call `eval-last-sexp` from the position behind the last closing parenthesis in an elisp scratch buffer.

**Comment by spacerainbow000** [comment] 2017-11-22 22:54
oops! it works now. any suggestions on how I should have the buffer open split screen style automatically when there is an error, and close when rustfmt succeeds, or will it be left as an exercise to the reader?

**Comment by brotzeit** [comment] 2017-11-23 08:56
I use this #246.

**Closed** 2017-12-07 20:40 UTC
