### ISSUE TITLE
compile-command=`cargo build` breaks workflow

### ISSUE THREAD

**Issue by Dushistov** [rust-lang/rust-mode#226] opened 2017-08-04 07:33 UTC
After #216 my workflow become broken.

For example,

1. I open lib.rs
2. `M-x compile` and choose `cargo check`
3. jump to buffer with another file in the same crate and invoke `M-x recompile`,
   `emacs` instead of `cargo check` calls `cargo build`,

This is especially wrong for crates that may be compiled only with specific `target` and not default one. So if type `cargo build   --target=arm-linux-androideabi` and then recompile
you got compile time error, because it invokes `cargo build` instead of `cargo build   --target=arm-linux-androideabi`.

**Comment by tromey** [comment] 2017-08-05 17:04
I tend to think that that patch should be reverted.  People who really want to force `compile-command` like that can easily do it in their mode hook.  But, it seems clear now that the change is not appropriate for all cases.

**Comment by RalfJung** [comment] 2017-08-05 18:11
So having to customize the mode hook is expected behavior? :/

I suppose that's just how emacs works, and this mode cannot do much about that. In my experience, "customize the mode hook" is equivalent to "random mutation of lisp code until it does what I want it to do". I had hoped this one particular customization maybe could be avoided. Oh well. (These problems are the reason why I now avoid using emacs if I can...)

**Comment by tromey** [comment] 2017-08-05 20:08
> So having to customize the mode hook is expected behavior? :/

Yeah, it's pretty normal.  I think the problem with the approach taken here is that it sets `compile-command` locally, so that any changes one makes don't apply across the other buffers in the project.  That seems like a minus.

One alternate approach that might work would be to push the cargo build command onto `compile-history`, maybe with some heuristic like "topmost entry doesn't already start with `"cargo"`".  This would make `M-x compile` default to `cargo build` but without interfering with any changes that have been made.

**Comment by Aankhen** [comment] 2017-08-10 15:46
Oops. Sorry about that. Let me try @tromey’s alternative.

**Comment by tromey** [comment] 2017-08-14 06:40
That would be reasonable as well, I think.  Nothing even says we have to use compilation mode; it is convenient but there are other bugs showing how it doesn't always line up exactly with what rust does.

**Comment by iwillspeak** [comment] 2017-09-17 12:54
A temporary work around for this:

```elisp
(add-hook 'rust-mode-hook
          (lambda ()
            (kill-local-variable 'compile-command))
```

**Comment by rightfold** [comment] 2017-10-07 10:11
It should be possible to set a flag that prevents rust-mode from ever touching `compile-command`. I set `compile-command` myself on each Emacs session depending on what project I am working on (typically `(cd ~/... && cargo test)`), and bind `<f5>` to `compile`.

**Comment by nikomatsakis** [comment] 2017-10-13 09:55
I second the complaint in this issue. The fact that `compile-command` became buffer-local  was really confusing me for a while!

**Comment by nikomatsakis** [comment] 2017-10-13 09:57
Admittedly, I apparently merged the original PR. =)

I feel like I remember reading that compile-command has some ability to customize the default command on a per-mode basis...but perhaps not.

**Comment by iwillspeak** [comment] 2017-10-14 08:11
Yay! I now have `C-c b` bound to `rust-compile` to run `cargo build`, and I can use `M-x compile` to run whatever compilation command I have chosen at the moment. For reference [here is my use-package config](https://github.com/iwillspeak/.emacs.d/blob/master/init.el#L323).

**Comment by tromey** [comment] 2017-10-17 16:35
I think this is done now.

**Closed by tromey** 2017-10-17 16:35 UTC

**Comment by username231419** [comment] 2026-03-13 12:08
I think it is convenient to have `rust-mode` buffers suggest `cargo build` by default.  The workflow issue could be fixed upstream, or by evaluating this advice:

```elisp
(define-advice recompile (:around (fn &optional edit-command) keep-compile-command)
  "Reuse the last `compile-command' from a \"*compilation*\" buffer."
  (let* ((buf (get-buffer "*compilation*"))
        (compile-command (if buf
                             (buffer-local-value 'compile-command buf)
                           compile-command)))
    (funcall fn edit-command)))
```
