### ISSUE TITLE
rust-format-buffer resets all code blocks to "shown" under hideshow

### ISSUE THREAD

**Issue by codesections** [rust-lang/rust-mode#350] opened 2020-01-28 21:54 UTC
Thanks for the great package.

I use `rust-mode` along with the builtin Emacs `hs-minor-mode`.  Unfortunately, the two do not play very well together.  Specifically, whenever I run `rust-format-buffer` and rustfmt makes any changes to the code, all code is displayed again – even code that was previously marked as hidden using hideshow.  If rustfmt does *not* make any changes, then no hidden code is incorrectly shown.

I suspect that this is related to #260 (and #143 mentions overall integration with HideShow).

**Comment by mookid** [comment] 2020-05-21 18:04
hi @codesections, I can't reproduce any more, likely since #371. Closing it, feel free to reopen if it is still a problem.

**Closed by mookid** 2020-05-21 18:04 UTC
